### ISSUE TITLE
Add Linting

### ISSUE THREAD

**Issue by ogrady** [FlussuferOrga/Botgart#137]
Add tslint to the project. 
Especially a rule for consistent use of quotes https://palantir.github.io/tslint/rules/quotemark/

**Comment by Xyaren** [comment]
Yes, I already planned on doing that, also this ensures to keep a consistent code style across the project

**Comment by ogrady** [comment]
Not necessarily a work order for you, but a general issue that should be done by _someone_. Possibly me. 😜
Just wanted to write it down, so it won't be forgotten.

**Comment by ogrady** [comment]
Should also get https://palantir.github.io/tslint/rules/no-unused-variable/ as I tend to skip on cleaning up my imports.

**Comment by Xyaren** [comment]
Just experimenting with the rules... I got it down to a few hundret errors...

**Comment by Xyaren** [comment]
Linting was enabled within #146.
Now we have to check the configured rules, and gradually enable more rules while also fixing the existing codebase.
